export const API_USER_REGISTRATION = '/api/user/registration'
export const API_USER_LOGIN = '/api/user/login'
export const API_USER_AUTH = '/api/user/auth'

export const API_TYPE = 'api/type'
export const API_BRAND = 'api/brand'
export const API_DEVICE = 'api/device'
export const API_BASKET = 'api/basket'
export const API_BASKET_DEVICE = 'api/basket_device'
export const API_BASKET_DEVICE_GROUP = 'api/basket_device/group'
export const API_PHOTO = 'api/photo'
export const API_PHOTO_GROUP = 'api/photo/group'