export const MAIN_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const SHOP_ROUTE = '/shop'
export const BASKET_ROUTE = '/basket'
export const DEVICE_ROUTE = '/device'

export const STOKE_ROUTE = '/stoke'
export const SHIPPING_AND_PAYMENT_ROUTE = '/shipping_and_payment'
export const ARTICLES_ROUTE = '/articles'
export const ABOUT_STORE_ROUTE = '/about_store'
export const CABINET_ROUTE = '/cabinet'

export const NOT_FOUND_ROUTE = '/notfound'